# Generated by Django 4.2 on 2023-05-01 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyModel',
            new_name='Product',
        ),
    ]
